# Makefile

LIBRARY    := liblcd-hd44780.a
PROJBASE   := ../..
BUILD_DIR  := ./build
VPATH_DIRS := ./src
LIB_DIR    := ./lib

include $(PROJBASE)/mk/config.mk
include $(PROJBASE)/mk/toolchain.mk

OBJS += $(BUILD_DIR)/Lcd.o

include $(PROJBASE)/mk/library.mk
