# Makefile

PROGNAME   := monitor
BUILD_DIR  := build
PROJBASE   := ..
VPATH_DIRS := ./src

OBJS := $(BUILD_DIR)/commands.o
OBJS += $(BUILD_DIR)/commandAdc.o
OBJS += $(BUILD_DIR)/commandCrc.o
OBJS += $(BUILD_DIR)/commandDebug.o
OBJS += $(BUILD_DIR)/commandDelay.o
OBJS += $(BUILD_DIR)/commandDig.o
OBJS += $(BUILD_DIR)/commandDump.o
OBJS += $(BUILD_DIR)/commandEeprom.o
OBJS += $(BUILD_DIR)/commandFlash.o
OBJS += $(BUILD_DIR)/commandHeap.o
OBJS += $(BUILD_DIR)/commandId.o
OBJS += $(BUILD_DIR)/commandMap.o
OBJS += $(BUILD_DIR)/commandMem.o
OBJS += $(BUILD_DIR)/commandPwm.o
OBJS += $(BUILD_DIR)/commandReset.o
OBJS += $(BUILD_DIR)/commandStack.o
OBJS += $(BUILD_DIR)/commandSystem.o
OBJS += $(BUILD_DIR)/commandUptime.o
OBJS += $(BUILD_DIR)/commandVer.o
OBJS += $(BUILD_DIR)/globals.o
OBJS += $(BUILD_DIR)/main.o
OBJS += $(BUILD_DIR)/utils.o

include $(PROJBASE)/mk/program.mk
